name: 'rawls-build-tag-publish'
description: 'builds rawls from a branch and publishes it so that it can be deployed'
inputs:
  rawls-branch:
    description: 'The branch of brawls to deploy. If not present, the branch will be determined from the pull request or github event.'
    required: false
    default: ''
  token:
    description: github token for access to kick off a job in the private rep
    required: true
outputs:
  rawls-custom-version-json:
    description: 'the json representation of the version of rawls that was built and deployed'
    value: ${{ steps.render-rawls-version.outputs.custom-version-json }}
  rawls-ref:
    description: 'the branch, tag or SHA of rawls that was built and deployed'
    value: ${{ inputs.rawls-branch || steps.extract-branch.outputs.ref }}

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'

    - name: Bump the tag to a new version
      uses: databiosphere/github-actions/actions/bumper@bumper-0.2.0
      id: tag
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ inputs.token }}
        RELEASE_BRANCHES: main
        WITH_V: true

    - name: Extract branch
      id: extract-branch
      if: ${{ (inputs.rawls-branch == '') }}
      shell: bash
      run: |
        GITHUB_EVENT_NAME=${{ github.event_name }}
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          GITHUB_REF=${{ github.ref }}
          GITHUB_SHA=${{ github.sha }}
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          GITHUB_REF=refs/heads/${{ github.head_ref }}
          GITHUB_SHA=${{ github.event.pull_request.head.sha }}
        else
          echo "Failed to extract branch information"
          exit 1
        fi
        
        echo "ref=$GITHUB_REF" >> $GITHUB_OUTPUT
        echo "name=$GITHUB_SHA" >> $GITHUB_OUTPUT

    - name: dispatch build to terra-github-workflows
      uses: broadinstitute/workflow-dispatch@v3
      with:
        workflow: rawls-build
        repo: broadinstitute/terra-github-workflows
        ref: refs/heads/main
        token: ${{ inputs.token }}
        inputs: '{ "repository": "${{ github.event.repository.full_name }}", "ref": "${{ inputs.rawls-branch || steps.extract-branch.outputs.ref }}", "rawls-release-tag": "${{ steps.tag.outputs.tag }}" }'

    - name: Render Rawls version
      id: render-rawls-version
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: |
        echo "$GITHUB_CONTEXT"
        echo "custom-version-json={\\\"rawls\\\":{\\\"appVersion\\\":\\\"${{ steps.tag.outputs.tag }}\\\"}}" >> $GITHUB_OUTPUT
