FROM broadinstitute/rawls:dev

RUN wget http://download-aws.ej-technologies.com/jprofiler/jprofiler_linux_9_1.tar.gz && tar -xvf jprofiler_linux_9_1.tar.gz && rm jprofiler_linux_9_1.tar.gz

ADD docker/run-with-jprofiler.sh /etc/service/rawls/run
