mysql:
  image: mysql/mysql-server:5.7.15
  environment:
    MYSQL_ROOT_PASSWORD: rawls-test
    MYSQL_USER: rawls-test
    MYSQL_PASSWORD: rawls-test
    MYSQL_DATABASE: testdb
  ports:
    - "3310:3306"
  volumes:
    - ./docker/sql_validate.sh:/working/sql_validate.sh

integration-tests:
  image: broadinstitute/scala-baseimage
  environment:
    GIT_MODEL_HASH: $GIT_MODEL_HASH
  working_dir: /rawls
  links:
    - mysql:mysql
  volumes:
    - jar-cache:/root/.ivy
    - jar-cache:/root/.ivy2
    - /app/rawls-integration.conf:/etc/rawls.conf:ro
    - /app//rawls-account.pem:/etc/rawls-account.pem:ro
    - /app/billing-account.pem:/etc/billing-account.pem:ro
    - /etc/localtime:/etc/localtime:ro
    - /tmp/rawls:/rawls
  entrypoint:
    - sbt
    - -Dsbt.log.noformat=true
    - -Dmysql.host=mysql
    - -Dmysql.port=3306
    - -Dconfig.file=/etc/rawls.conf
    - clean
    - it:test
