ALTER TABLE WORKFLOW_FAILURE DROP FOREIGN KEY FK_WF_FAILURE_SUB;

ALTER TABLE WORKFLOW_FAILURE DROP FOREIGN KEY FK_WF_FAILURE_ENTITY;

ALTER TABLE WORKFLOW_ERROR DROP FOREIGN KEY FK_WF_ERR_FAILURE;

#store the WORKFLOW_FAILURE_ID that the new WORKFLOW will originate from
ALTER TABLE WORKFLOW ADD COLUMN TEMP_WORKFLOW_FAILURE_ID bigint(20) unsigned default null;

INSERT INTO WORKFLOW (SUBMISSION_ID, STATUS, STATUS_LAST_CHANGED, entity_id, record_version, TEMP_WORKFLOW_FAILURE_ID)
	SELECT wff.SUBMISSION_ID, 'Failed', s.DATE_SUBMITTED, wff.entity_id, 0, wff.id
	FROM WORKFLOW_FAILURE wff JOIN SUBMISSION s ON wff.SUBMISSION_ID = s.ID;

INSERT INTO WORKFLOW_MESSAGE (WORKFLOW_ID, MESSAGE)
	SELECT wf.ID, we.ERROR_TEXT FROM WORKFLOW_ERROR we JOIN WORKFLOW wf on wf.TEMP_WORKFLOW_FAILURE_ID = we.WORKFLOW_FAILURE_ID;

UPDATE SUBMISSION_VALIDATION sv
	JOIN WORKFLOW wf on sv.WORKFLOW_FAILURE_ID = wf.TEMP_WORKFLOW_FAILURE_ID
	SET sv.WORKFLOW_FAILURE_ID = null, sv.WORKFLOW_ID = wf.ID;


ALTER TABLE SUBMISSION_VALIDATION DROP FOREIGN KEY FK_SUB_VALIDATION_FAIL;

ALTER TABLE SUBMISSION_VALIDATION DROP INDEX FK_SUB_VALIDATION_FAIL;

ALTER TABLE SUBMISSION_VALIDATION DROP COLUMN WORKFLOW_FAILURE_ID;

ALTER TABLE WORKFLOW DROP COLUMN TEMP_WORKFLOW_FAILURE_ID;

DROP TABLE WORKFLOW_ERROR;

DROP TABLE WORKFLOW_FAILURE;