FROM us.gcr.io/broad-dsp-gcr-public/scala-baseimage

COPY src /app/src
COPY minnie-kenny.sh /app
COPY test.sh /app
COPY project /app/project
COPY build.sbt /app

WORKDIR /app

ENTRYPOINT ["bash", "test.sh"]
