FROM broadinstitute/scala-baseimage:jdk11-2.12.11-1.4.7

COPY src /app/src
COPY minnie-kenny.sh /app
COPY test.sh /app
COPY project /app/project
COPY build.sbt /app

WORKDIR /app

ENTRYPOINT ["bash", "test.sh"]
