FROM hseeberger/scala-sbt:graalvm-ce-21.0.0-java11_1.5.0_2.13.5

COPY src /app/src
COPY minnie-kenny.sh /app
COPY test.sh /app
COPY project /app/project
COPY build.sbt /app

WORKDIR /app

ENTRYPOINT ["bash", "test.sh"]
