name: quicksilver-benchmarks
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: test.js
