name: quicksilver-benchmarks
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:

      - name: dispatch build to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4.0.0
        with:
#          run-name: "${{ env.RAWLS_BUILD_RUN_NAME }}"
          workflow: quicksilver-k6
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/da_CORE-363_k6benchmarks
          token: ${{ secrets.BROADBOT_TOKEN }} # github token for access to kick off a job in the private repo
          inputs: '{}'

#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup K6
#        uses: grafana/setup-k6-action@v1
#
#      - name: Run local k6 test
#        uses: grafana/run-k6-action@v1
#        env:
#          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
#          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
#        with:
#          path: core/src/test/k6/script.js
