name: workflows-complex-canary-prod-test
'on':
  schedule:
    - cron: "0 */3 * * *"  # run every 3 hours
  workflow_dispatch:
  pull_request: # TODO: remove this before merging
    branches: [ develop ]

jobs:
  run-complex-canary-prod-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4.0.0
        with:
          workflow: workflows-canary-prod-test
          run-name: "workflows-complex-canary-prod-test-${{ github.run_id }}-${{ github.run_attempt }}"
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/sps_complex_canary_test # TODO: change to 'main' before merging
          token: ${{ secrets.BROADBOT_TOKEN }} # GitHub token for access to kick off a job in the private repo
          wait-for-completion-timeout: 4h
          inputs: '{
            "run-name": "workflows-complex-canary-prod-test-${{ github.run_id }}-${{ github.run_attempt }}",
            "workspace-namespace": "broad-firecloud-dsde",
            "workspace-name": "complex-featured-workflow",
            "method-namespace": "gatk",
            "method-name": "five-dollar-genome-analysis-pipeline",
            "entity-type": "sample",
            "entity-id": "na12878_real_small"
          }'

  report-workflow:
    uses: broadinstitute/sherlock/.github/workflows/client-report-workflow.yaml@main
    with:
      notify-slack-channels-upon-workflow-failure: "#dsp-analysis-prod-alerts"
      notify-slack-custom-icon: ":sad-terra:"
    permissions:
      id-token: write
